### ISSUE TITLE
question

### ISSUE THREAD

**Issue by ykingliu** [NickWilkinson37/voxseg#1]
hi, the project works well, but i don't find anything about model training. Can you share the model training code, thanks a lot

**Comment by NickWilkinson37** [comment]
Hi, I'm glad to hear the project is working well for you. Currently the training scripts are not included, as I would like to implement model training in a nice and flexible manner, which will require some changes to other parts of the project.

I can let you know when that is ready, or if you would like to train your own model more urgently I could maybe add the training code 'as is' to the readme for now, with some basic documentation, and you can see if you can get it working your side.

**Comment by ykingliu** [comment]
ok, thanks, please add the training code 'as is' to the readme, with some basic documentation. Let me try if it can work on my side.

**Comment by ykingliu** [comment]
hi, @NickWilkinson37, Please forgive me for the interruption， i would like to know when the training code is ready, i really need your help. thank you very much

**Comment by NickWilkinson37** [comment]
Hi @ykingliu, my apologies for the slow reply. I maintain this repo in my spare time, which has unfortunately been a bit short lately. I will do my best to get something up with some instructions later today, I'll let you know here as soon as it's done.

**Comment by NickWilkinson37** [comment]
Hi @ykingliu, once again I apologise for the slow reply. I have uploaded a training script in the root directory and added instructions to the README.

I'm sorry it took so long, it turned out I needed to make some changes in the package for it to work properly. I hope you find it useful!

**Comment by ykingliu** [comment]
Hi @NickWilkinson37 Thank you for your reply. I see your training code, I will try it later. I really appreciate your help

**Comment by NickWilkinson37** [comment]
No problem, glad to help!
