### ISSUE TITLE
Prior issue

### ISSUE THREAD

**Issue by Lhemamou** [NickWilkinson37/voxseg#4]
Hi Nick,

I just wanted to double check with you if prior value was ok !

In the code we have these following : 
`        prior = np.array([(1-speech_thresh) * speech_w_music_thresh,
                        speech_thresh * speech_w_music_thresh,
                        (1-speech_thresh) * (1-speech_w_music_thresh),
                        (1-speech_thresh) * speech_w_music_thresh])`

the first and last value seem the same. Should the last value be changed to `(speech_thresh) * (1-speech_w_music_thresh)` ?

Thanks again for all the great work !

Léo

**Comment by NickWilkinson37** [comment]
Hi Léo,

Thanks for the comment, I really appreciate when users reach out to help me improve the package!

I have double checked the value, and I believe it is correct as is. The reason being the first value determines the threshold applied to the "CleanSpeech" output, and the last value determines the threshold applied to the "Speech+Noise" output. One can think of both of these as being a "speech" class, and so they both have the same threshold applied. Whereas the third output, for example, is the "Speech+Music" output, and so the `speech_w_music_thresh` interacts with that output differently to the other two "speech" outputs which do not indicate the presence of music.

For a full discussion regarding the prior value, as well as an example of how it works, refer to my comment here:
https://github.com/NickWilkinson37/voxseg/issues/2#issuecomment-854540906

Let me know if that helps, or if I'm maybe missing something. I'm glad to hear you are finding the work useful!

Nick

**Comment by Lhemamou** [comment]
Thanks you a lot Nick for all your answers !!! In term a feedback, I can tell you that the network is working quite well in term of noisy environment (bad microphones and so on).

As the first value of prior and last one are the same, should you consider to add another variable to control the prior for Speech+Noise ?

Thanks again Nick, I close the issue :)
